### ISSUE TITLE
Can't upload to iTunes

### ISSUE THREAD

**Issue by Taarna** [apptentive/apptentive-ios#163]
Hi guys.

We tried uploading the app to iTunes yesterday, but Application Loader kept showing this message:

<img width="633" alt="screen shot 2015-10-23 at 08 56 55" src="https://cloud.githubusercontent.com/assets/4928442/10686459/95651904-7964-11e5-9ffd-8ae55dd136fd.png">

At first we thought Apple is having some problems but then someone on StackOverflow suggested that the message might be caused by Info.plist from a 3rd party library. We added CFBundleVersion, CFBundleShortVersionString and CFBundleIdentifier to Apptentive's Info.plist and the upload started working.

---
Update:
Found [this link](https://github.com/Jonge/Cocoapods-frameworks-version-number-fix) after posting the issue.

**Comment by pashan** [comment]
Please update, we need it as soon as possible.Waiting, please please, update it.

**Comment by frankus** [comment]
We are hard at work on a fix. 

The source of this issue is that the ApptentiveResources.bundle that's generated includes an Info.plist file that doesn't have the bundle identifier (CFBundleIdentifier), bundle version (CFBundleVersion), and bundle short version string (CFBundleShortVersionString) keys set. As a workaround, you can set them manually (we'll be using the values 'com.apptentive.resources-ios', 2.0, and 2.0, respectively).

**Comment by Taarna** [comment]
Thank you!

**Comment by pedromancheno** [comment]
Worked like a charm

**Comment by frankus** [comment]
This should be fixed in version 2.0.4.

**Comment by frankus** [comment]
Just a note that we missed a file in the CocoaPods version in 2.0.4. 2.0.5 addresses this, so please run a `pod update` if you are still seeing the issue.
