### ISSUE TITLE
ATIntercationUpgradeMessageViewController.xib file is set to build for a version older than...

### ISSUE THREAD

**Issue by pashan** [apptentive/apptentive-ios#164]
When building app for store, getting warning:

ATInteractionUpgradeMessageViewController.xib

This file is set to build for aversion older than the project deployment target. Functionality may be limited.

xCode 7.1 Please fix this.

**Comment by frankus** [comment]
Because our library supports devices back to iOS 7.0, we can't update the deployment target of this xib file to a version higher than 7.0. Although it's annoying, you can safely ignore this warning. 

In a future release this xib will be merged with the new storyboard file, so this warning should go away. Stay tuned :)

**Comment by jeffctown** [comment]
I would love a fix for this.

**Comment by frankus** [comment]
The 2.1.0 release incorporates the upgrade dialog into a storyboard file, so you should no longer see these warnings using 2.1.0.
