### ISSUE TITLE
Cannot open message center after upgrade from SDK 1.7 => 3.0

### ISSUE THREAD

**Issue by tigerline** [apptentive/apptentive-ios#175]
Xcode 7.3
iPhone 6 Plus / iOS 9.3.1
My old app Version: Apptentive iOS SDK 1.7
My new app Version: Apptentive iOS SDK 3.0

Steps:
- Install and launch old app version (currently live, from App Store)
- Update with new app version (debug version via Xcode)
- Launch new app, wait 20 sec
- Console shows "[error] Activity feed result is not NSDictionary!"
- Open message center => **Error** "We’re attempting to connect. Thanks for your patience!"

**Comment by frankus** [comment]
There's definitely a bug, in that the "[error] Activity feed result is not NSDictionary!" should not be displayed (it's a normal consequence of a PUT request to the endpoint that notifies us that the app and/or SDK has been updated, which returns 204 and an empty response rather than JSON). We will get this fixed in the next release. 

That message should be followed closely by "Received remote Interactions from Apptentive." in the log. It's possible that you happened to test it when our API server was under an unusual amount of load, and that the remote interactions request was taking longer than it normally would. If you relaunch the app, the interactions should download normally within the first 30 seconds or so of runtime. 

Let me know if this continues to be a problem and I'll investigate further.

**Comment by sohos** [comment]
Same error here
iPhone 6, iOS 9.3.1, Apptentive SDK 2.1.3
But on iPhone 5, iOS 9.3.1, Apptentive SDK 2.1.3 working
Both devices are with the same app version from App store
Updated apptentive SDK to 3.0.0, same situation
It stopped to work on iPhone 6 around month ago

**Comment by frankus** [comment]
After some more investigation, it looks like this is a problem on our server. There are multiple API requests made at startup and this upgrade exposed a race condition in one of them. 

We have a patch live that should address this on our server. If you're still seeing the issue, please let us know/reopen the issue.
