### ISSUE TITLE
Error in engaging events

### ISSUE THREAD

**Issue by mayur43s** [apptentive/apptentive-ios#183]
When I'm trying to engage an event by using the following code:
`[[Apptentive sharedConnection] engage:@"got_RSVP" fromViewController:self];` from an viewController and here are the logs printed on console:

2016-09-17 16:54:26.638 [info] Engage Apptentive event: local#app#got_RSVP

Just below this there's another log saying:

2016-09-17 16:54:26.651 [info] Interaction NUMERIC_ID predicate failed evaluation.
2016-09-17 16:54:26.653 [info] Interaction NUMERIC_ID predicate failed evaluation.

And when I look at the dashboard the event count does not increase.

Pls have a look into this issue.

**Comment by frankus** [comment]
The "failed evaluation" is the normal behavior when either a "Who"(segmentation) requirement isn't being met, or one of the timing settings (like the "wait N days before showing") isn't being met (although admittedly it's a poorly-worded log message). 

Unfortunately we currently don't have a way to get more transparency into exactly which isn't being met. 

Most commonly you'll see that message because you haven't waited long enough between installing the app and triggering the event. You can speed up the process by temporarily changing your device's (or, in the simulator, your computer's) clock forward a few days.
