### ISSUE TITLE
After updating to version 3.3.2 Cocoapod is failing

### ISSUE THREAD

**Issue by cromandini** [apptentive/apptentive-ios#189]
I'm using apptentive-ios via Cocoapods. Previously was using version 3.3.0 with any issues but after a pod update (library updated to version 3.3.2) now I have this failure:

<img width="973" alt="screen shot 2016-11-16 at 16 46 42" src="https://cloud.githubusercontent.com/assets/1238813/20362996/4f230636-ac1c-11e6-8858-550ef7cbd7a0.png">

What can be wrong, is there any additional setting I could be missing?
Thanks!

**Comment by cromandini** [comment]
Guys, if I change that import back to `#import "Apptentive.h"` (as it was in the previous version) the issue is fixed.

**Comment by frankus** [comment]
With our transition to building dynamic frameworks (for e.g. Carthage support), this bug slipped in. 

If you're able to use the `use_frameworks!` directive in your podfile, that will avoid this issue. Otherwise you may have to make the change you mentioned manually until we release our next version.
