### ISSUE TITLE
Crash on iOS 11 in ApptentiveMessageCenterViewController

### ISSUE THREAD

**Issue by tomhartnett** [apptentive/apptentive-ios#207]
Hi, we are seeing a crash in our app on iOS 11.  From the stacktrace, it looks like it is related to calling dequeueReusableCellWithIdentifier more than once.  And the cell identifier, "ContextMessage", indicates it is happening in Apptentive, in the cellForRowAtIndexPath method in ApptentiveMessageCenterViewController.

I found this thread where a UIKit engineer states that this NSInternalInconsistencyException is a new check in iOS 11:  https://github.com/kif-framework/KIF/issues/1007

We are on v3.4.1 still, so I'm not sure if this issue has already been found and fixed in a later release?  The code in cellForRowAtIndexPath looks similar in the latest version.

Stacktrace:
Fatal Exception: NSInternalInconsistencyException
Attempted to dequeue multiple cells for the same index path, which is not allowed. If you really need to dequeue more cells than the table view is requesting, use the -dequeueReusableCellWithIdentifier: method (without an index path). Cell identifier: ContextMessage, index path: <NSIndexPath: 0xc000000000000016> {length = 2, path = 0 - 0}

**Comment by frankus** [comment]
This is a known issue when linking any of the 3.x and older Apptentive SDKs with the iOS 11 SDK. We made some architectural changes in 4.0 that avoid this particular crash. 

Because the incremental effort to upgrade to 4.x is not much greater than upgrading to another 3.x release, we decided not to issue a fix to the 3.x SDK and are encouraging folks to upgrade to the latest 4.0 SDK.

**Comment by maskedpear** [comment]
Any easy way to reproduce this crash? We see it reported on Crashlytics and wanted to replicate it before installing latest version. Thank you.
